service: testeserverless

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
     - aws-sdk
    target: node14
    platform: node
    concurrency: 10

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    COUNTAPI_NAMESPACE: ${env:COUNTAPI_NAMESPACE}
    COUNTAPI_KEY: ${env:COUNTAPI_KEY}

package:
  individually: true

functions:
  consultAccess:
    handler: src/functions/consultAccess.handler
    events:
    - http:
        path: /consultAccess
        method: GET
        cors: true
  increaseAccess:
    handler: src/functions/increaseAccess.handler
    events:
    - http:
        path: /increaseAccess
        method: POST
        cors: true